### ISSUE TITLE
Applications

### ISSUE THREAD

**Issue by Freshmilkymilk** [ArdaCraft/IssueTracker#25]
Need to figure out how we're going to do applications.

Some options:
- Create a whole page, with back end from scratch.
- Find a plugin for discourse
- Make applications on the forums, like they were when the server first started.

**Comment by Atlantispy** [comment]
Could be done using a google form?

**Comment by dags-** [comment]
Could this potentially be done in-game if there's to be a plot server/world?
Most plots plugins have a `/review` command that alerts moderators to go assess the builds. Everything can be handled in-game, instead of someone having to jump back-and forth between website to see applications, and server to `/promote`

**Comment by Atlantispy** [comment]
I think that for applications Fornad wants to have more than just a build involved in order to approve them, he wants to be able to see why they want to join.

**Comment by dags-** [comment]
Oh. k

**Comment by Freshmilkymilk** [comment]
https://forums.ardacraft.me/c/applications
