### ISSUE TITLE
Crash when selecting Clear Water in Quality tab.

### ISSUE THREAD

**Issue by Atlantispy** [ArdaCraft/IssueTracker#38]
http://pastebin.com/2ettXVzK 

I'm now able to log on and not crash, however I do crash when I try and toggle Clear Water from Optifine, unsure if the crash is exclusive to me.

**Comment by dags-** [comment]
This issue tracker is essentially a to-do list and progress tracking tool for the technical/back-end stuff.
The Support category of the new forums should be used for user crash-reports and difficulties.

While I'm here though, there doesn't look to be the actual crash included on that log (although there are plenty of errors). You might have a crash-report in the 'crash-reports' folder of your installation dir that might give more clues.

The last thing that is complaining on your log is voxelmap. I presume you're running on the launcher since it's not in the profile-installer version of the modpack - you could try run without (may be that optifine is not 100% compatible with it or something).
