### ISSUE TITLE
Chain blocks.

### ISSUE THREAD

**Issue by Atlantispy** [ArdaCraft/IssueTracker#54]
Chain blocks currently can't be placed with a different orientation as if they are on a log.

**Comment by dags-** [comment]
What are chain blocks?

**Comment by Atlantispy** [comment]
"Chain coil block", ID 1258, it's basically the same as the rope block.

**Comment by dags-** [comment]
It has been added as a 'BLOCK' type rather than a 'LOG' type:
https://github.com/ArdaCraft/BlockPack-Conquest/blob/master/assets/acblocks/definitions/decoration/chains/chain_coil.json

Don't use it as it is currently. When the blockpack is updated to fix, the new log block won't be assigned the same ID.

**Comment by dags-** [comment]
Could probably be squeezed into update# - @whoever does the blockpacks

**Comment by Freshmilkymilk** [comment]
Will be added to the next blockpack update.
